import datetime
import calendar
import requests
import pandas as pd

from io import BytesIO
import smtplib
from email.message import EmailMessage




def get_page():
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        # 'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive',
        'Referer': 'https://mywallace.in/',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'frame',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'same-origin',
        'Pragma': 'no-cache',
        'Cache-Control': 'no-cache',
    }

    response = requests.head('https://mywallace.in/Wallace/index.php', headers=headers)
    return response.headers, response.cookies

def get_login(user, password):
    headers, cookies = get_page()
    payload = {
        'module': 'Users',
        'action': 'Authenticate',
        'return_module': 'Users',
        'return_action': 'Login',
        'user_name': 'sfe',
        'user_password': 'user@123',
        'Login': 'LOGIN'

    }

    with requests.Session() as session:
        r = session.post(r'https://mywallace.in/Wallace/index.php', data=payload)

        return r.cookies, r.headers





def get_session():
    s = requests.Session()
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        # 'Accept-Encoding': 'gzip, deflate, br',
        'Upgrade-Insecure-Requests': '1',
        'Connection': 'keep-alive',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'none',
        'Sec-Fetch-User': '?1',
        'Pragma': 'no-cache',
        'Cache-Control': 'no-cache',
    }

    # get root page
    print('root page')
    response = s.get('https://mywallace.in/', headers=headers)

    # get login page
    print('login')
    response = s.get('https://mywallace.in/Wallace/index.php', headers=headers)
    pa, ua = list(get_aipl().values[0])
    data = {
        'module': 'Users',
        'action': 'Authenticate',
        'return_module': 'Users',
        'return_action': 'Login',
        'user_name': pa,
        'user_password': ua,
        'Login': 'LOGIN',
    }
    # get page post login
    response = s.post('https://mywallace.in/Wallace/index.php', data=data)


    params = {
        'action': 'index',
        'module': 'Home',
    }
    # Get home page after login
    response = s.get('https://mywallace.in/Wallace/index.php', params=params)


    params = {
        'module': 'Reports',
        'action': 'index',
        'smodule': 'STANDARD',
    }
    # Get standard reports page
    response = s.get('https://mywallace.in/Wallace/index.php', params=params)
    print('standard page')

    return s




def get_data(data=None, params=None, count_skip_rows=None):

    session = get_session()
    # Generate report as Xls
    response = session.post('https://mywallace.in/Wallace/index.php', params=params, data=data)
    print('xls generated')
    
    xldata = pd.read_excel(response.content, skiprows=count_skip_rows)
    return xldata





def get_aipl_automation_master():
    return pd.read_csv('https://docs.google.com/spreadsheets/d/1SXliYc5rGqJw3u1fR4BEMNMH9I8SnBdrmJII3CJ51Sw/export?format=csv&gid=1451827471').set_index('division')





def get_aipl():
    return pd.read_csv('https://docs.google.com/spreadsheets/d/1SXliYc5rGqJw3u1fR4BEMNMH9I8SnBdrmJII3CJ51Sw/export?format=csv&gid=732906079')



def get_default_dates(returnType='datetime', baseDate:str=None):
    if not(baseDate):
        baseDate = str(datetime.datetime.now().date())
    baseDate = datetime.datetime.strptime(baseDate, "%Y-%m-%d")
    fromDt = str(f"{baseDate.year}-{baseDate.month}-01")
    lastDay = calendar.monthrange(baseDate.year, baseDate.month)[1]
    toDt = str(f"{baseDate.year}-{baseDate.month}-{lastDay}")
    if returnType=='str':
        return fromDt, toDt
    if returnType=='datetime':
        return datetime.datetime.strptime(fromDt, '%Y-%m-%d'), datetime.datetime.strptime(toDt, '%Y-%m-%d')


def send_mail_with_excel(recipient_email=None, subject="WP-UTIL", content="Requested file from WP-UTIL", excel_file_path=None, excel_file_rb=None, file_name=None):

    subject_body=f"WP-UTILITY: {subject}"
    content_body=f"Report generated from WP Utility App with name {subject} and content {content}.\nThis is an autogenerated email. Please do not reply.\nWP-Utility\nWallace Pharmaceuticals"


    gua, gpa = list(get_aipl().values[1])
    msg = EmailMessage()
    msg['Subject'] = subject_body
    msg['From'] = gua
    msg['To'] = recipient_email
    msg.set_content(content_body)

    if excel_file_path:
        with open(excel_file_path, 'rb') as f:
            file_data = f.read()
        msg.add_attachment(file_data, maintype="application", subtype="xlsx", filename=file_name)
    if excel_file_rb:
        msg.add_attachment(excel_file_rb, maintype="application", subtype="xlsx", filename=file_name) #subtype : vnd.openxmlformats-officedocument.spreadsheetml.sheet

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(gua, gpa)
        smtp.send_message(msg)
        
        
def df_to_excel_rb(df):
    output = BytesIO()
    with pd.ExcelWriter(output) as writer:
        df.to_excel(writer)
    processed_data = output.getvalue()
    return processed_data    
    


def main():
    pass
if __name__ == '__main__':
    main()


